### ISSUE TITLE
ReferenceError: updateNetworkStats is not defined

### ISSUE THREAD

**Issue by damintsew** [aspectron/sia-node#2]
Hello

Guys, trying to setup sia-node & sia-cluster. And continuously receiving same error

Error:

```
2017-04-21 17:00:43  SIA-NODE instance identifier: 'AD-LINUX'
2017-04-21 17:00:43  init OK
2017-04-21 17:00:43  Sia daemon version: 1.2.0
2017-04-21 17:00:43  iris-rpc ad-linux connected to server @127.0.0.1:58481, SSL certificate is unauthorized
2017-04-21 17:00:43  undefined RPC Disconnect undefined
/home/sia/sia-node/node_modules/iris-stats/lib/monitors/network.js:113
                return dpc(self.networkStatsFreq, updateNetworkStats);
                                                  ^

ReferenceError: updateNetworkStats is not defined
    at /home/sia/sia-node/node_modules/iris-stats/lib/monitors/network.js:113:51
    at /home/sia/sia-node/node_modules/iris-stats/lib/monitors/network.js:41:24
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
WARNING - Child process 'SIA-NODE' exited with code 1
Restarting 'SIA-NODE'

```

 
My configuration:

```
siad@ad-linux:~/sia-node$ uname -a
Linux ad-linux 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
siad@ad-linux:~/sia-node$ node -v
v7.9.0
```

At same time I also have:

```
{

    // identifier : "<instance-name>",  // if not included, defaults to your host name
                                        // node will be identified by this name in sia cluster

    rpc : {

        // address : "<ip-of-sia-cluster-rpc-server>:58481",
        // or
        // port : <local-rpc-server-port-number>

        address : "127.0.0.1:58481",
        auth : "MY_AUTH"
    },

    siad : {
        host : 'http://localhost:9980',
        path : '/home/sia/sia',    // path to sia folder (where siad and siac resides)
                        // for example "/home/userfolder/sia/"
    }
}

```

**Comment by damintsew** [comment]
At same time on sia-cluster I have:

```
2017-04-21 17:11:06  N/A disconnect undefined undefined
2017-04-21 17:11:08  generic failure during auth: Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Error (native)
    at Decipher.Cipher.final (crypto.js:156:26)
    at decrypt (/home/sia/sia-cluster/node_modules/iris-rpc/iris-rpc.js:57:21)
    at Server.Interface.self.iface.rpc::auth::response (/home/sia/sia-cluster/node_modules/iris-rpc/iris-rpc.js:251:33)
    at Server.<anonymous> (/home/sia/sia-cluster/node_modules/iris-rpc/iris-rpc.js:364:29)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at TLSSocket.<anonymous> (/home/sia/sia-cluster/node_modules/iris-rpc/iris-rpc.js:94:23)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at TLSSocket.Readable.push (_stream_readable.js:135:10)
    at TLSWrap.onread (net.js:542:20)
2017-04-21 17:11:08  N/A disconnect undefined undefined

```
